client:
  netrc: false
  login: username # Not needed if you use .netrc file
  password: password # Not needed if you use .netrc file
  access_token: access_token # Not needed if you use .netrc file
github:
  labels:
    continuous_integration:
      passing: 'auto-tests-passing'
      failing: 'auto-tests-failing'
      pending: 'auto-tests-in-progress'
    review:
      passing: 'review-approved'
      failing: 'review-rejected'
      pending: 'review-in-progress'
    conflict: 'conflict-with-parent'
  branches:
    protected:
      - 'master'
      - 'preproduction'
      - 'production'
      - 'sandbox'
      - 'staging'
      - 'training'
    exclude:
      - '/^v\d{2}(?:\.\d+)+RC$/'
