exclude_paths:
  - vendor
detectors:
  DuplicateMethodCall:
    max_calls: 3
  LongParameterList:
    max_params: 5
  NestedIterators:
    max_allowed_nesting: 2
  IrresponsibleModule:
    enabled: false
  TooManyStatements:
    enabled: false
  UtilityFunction:
    public_methods_only: true
  UncommunicativeVariableName:
    enabled: false
