AllCops:
  DisplayCopNames: true

# -------------------------------------------------------------------------------------------------
# EXCEPTIONS
# These are rules that we adapted that are different from the default behavior of Rubocop.
# -------------------------------------------------------------------------------------------------

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

# We like a little longer line support, and 131 is an awesome number.
# See https://en.wikipedia.org/wiki/131_(number)
Metrics/LineLength:
  Max: 131

Metrics/MethodLength:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/IfUnlessModifier:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets
